CREATE TABLE "RECIPE" (
"RECIPE_ID" INTEGER NOT NULL,
"NAME" VARCHAR(23) NOT NULL,
"INGREDIENT_ID" INTEGER,
PRIMARY KEY ("RECIPE_ID"));

CREATE TABLE "INGREDIENT" (
"INGREDIENT_ID" INTEGER NOT NULL,
"NAME" VARCHAR(23) NOT NULL,
"AMOUNT" INTEGER NOT NULL,
"COMMON" BOOLEAN NOT NULL,
PRIMARY KEY ("INGREDIENT_ID"));

CREATE TABLE "RECIPEINGRENDIENT" (
"RECIPE_ID" INTEGER NOT NULL,
"INGREDIENT_ID" INTEGER NOT NULL,
"AMOUNT" INTEGER NOT NULL,
FOREIGN KEY ("INGREDIENT_ID") REFERENCES "INGREDIENT",
FOREIGN KEY ("RECIPE_ID") REFERENCES "RECIPE",
PRIMARY KEY ("INGREDIENT_ID","RECIPE_ID"));


CREATE TABLE INVENTORY (
"INVENTORY_ID" INTEGER NOT NULL,
"USER_ID" INTEGER NOT NULL,
"INGREDIENT_ID" INTEGER NOT NULL,
"AMOUNT" INTEGER NOT NULL,
FOREIGN KEY ("USER_ID") REFERENCES "USER",
FOREIGN KEY ("INGREDIENT_ID") REFERENCES "INGREDIENT",
PRIMARY KEY ("INVENTORY_ID"));

CREATE TABLE "UNIT" (
"UNIT_ID" INTEGER NOT NULL,
"LABEL" VARCHAR(23) NOT NULL,
"INGREDIENT_ID" INTEGER NOT NULL,
FOREIGN KEY ("INGREDIENT_ID") REFERENCES "INGREDIENT",
PRIMARY KEY ("UNIT_ID"));

CREATE TABLE "USER" (
"USER_ID" INTEGER NOT NULL,
"NAME" VARCHAR(23) NOT NULL,
PRIMARY KEY ("USER_ID"));


