auth0:
  audience: https://api-dev.kuehlfrank.de
spring:
    profiles: dev
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: validate
    datasource:
      url: jdbc:postgresql://localhost:5432/kuehlfrank
      username: kuehlfrank
      password: VOUfsdHHdsZhGSS14PxurdT1u
      initialization-mode: always
      initialize: true
      continue-on-error: true
    thymeleaf:
      cache: false
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: https://tomstein.eu.auth0.com/  
logging:
  level:
    org.hibernate:
      sql: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
name: dev-YAML
environment: development
webhook.secret: S0wHX2boUt8FfsF9T2lM5wb05eEsIPGfjY6j8zNXlDRVhhyM4C09hr75NzHLrttw