spring:
    profiles: test
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8095/auth/realms/kuehlfrank
            jwk-set-uri: http://localhost:8095/auth/realms/kuehlfrank/protocol/openid-connect/certs
name: test-YAML
environment: test
server:
  port: 8081



---
spring:
    profiles: prod
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8095/auth/realms/kuehlfrank
            jwk-set-uri: http://localhost:8095/auth/realms/kuehlfrank/protocol/openid-connect/certs
name: prod-YAML
environment: production
servers: 
    - www.abc.com
    - www.xyz.com